# Generated by Django 2.1 on 2018-08-06 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='temperatures',
            options={'verbose_name': 'temperatures', 'verbose_name_plural': 'temperatures'},
        ),
        migrations.AddField(
            model_name='temperatures',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
