# Generated by Django 2.1 on 2018-08-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180823_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='desired_temp',
            new_name='temp_variation',
        ),
    ]
